version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  app:
    image: levelness/devops-for-programmers-project-lvl1:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    depends_on:
      db:
        condition: service_healthy
